//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicorConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public int Id { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public string DMSFlag { get; set; }
        public string Status { get; set; }
        public string CompanyCode { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string ForeignName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Fax { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<short> PriceListNum { get; set; }
        public string Currency { get; set; }
        public string Country { get; set; }
        public string PaymentTerm { get; set; }
        public string GroupTax { get; set; }
        public string TaxCode { get; set; }
        public string BusinessRegistrationCertificate { get; set; }
        public string CustomerType { get; set; }
        public string LegalName { get; set; }
        public string GroupCode { get; set; }
        public bool ValidPayer { get; set; }
        public bool ValidSoldTo { get; set; }
        public bool ValidShipTo { get; set; }
        public string TerritoryCode { get; set; }
        public string SalesRepCode { get; set; }
        public bool AllowShipTo3 { get; set; }
        public bool AllowOTS { get; set; }
        public bool PrintStatements { get; set; }
        public string TermsCode { get; set; }
        public bool CreditHold { get; set; }
        public Nullable<System.DateTime> EstablishedDate { get; set; }
        public Nullable<int> CountryNum { get; set; }
        public string Email { get; set; }
        public bool ConsolidateSO { get; set; }
    }
}
