//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicorConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public string CompanyCode { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string ForeignName { get; set; }
        public string Address { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Fax { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public string PriceListNum { get; set; }
        public string Currency { get; set; }
        public string Country { get; set; }
        public string PaymentTerm { get; set; }
        public string GroupTax { get; set; }
        public string TaxCode { get; set; }
        public string BusinessRegistrationCertificate { get; set; }
        public string CustomerType { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public string Status { get; set; }
        public string SystemLog { get; set; }
        public string DMSFlag { get; set; }
    }
}
