//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicorConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUST_OVER_DUE
    {
        public int Id { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public string DMSFlag { get; set; }
        public int CustomerId { get; set; }
        public string CustomerCode { get; set; }
        public string CompanyCode { get; set; }
        public string PaymentTerm { get; set; }
        public string MonthID { get; set; }
        public decimal CreditLimit { get; set; }
        public decimal BalanceDue { get; set; }
        public decimal OverDue { get; set; }
    }
}
