//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicorConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_INFO
    {
        public int Id { get; set; }
        public string Company { get; set; }
        public Nullable<int> Custnum { get; set; }
        public string CustID { get; set; }
        public Nullable<double> CreditLimit { get; set; }
        public Nullable<double> Balance { get; set; }
        public string ListCode { get; set; }
        public Nullable<double> OverDue { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Option4 { get; set; }
        public string Option5 { get; set; }
        public string PrcSysRevID { get; set; }
        public string CusSysRevID { get; set; }
        public string DMSFlag { get; set; }
    }
}
