//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicorConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public string CompanyCode { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerType { get; set; }
        public string CustomerName { get; set; }
        public string FullAddress { get; set; }
        public string Address { get; set; }
        public string Ward { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string SalesRepCode { get; set; }
        public string Phone1 { get; set; }
        public string Fax { get; set; }
        public string GroupTax { get; set; }
        public string TaxCode { get; set; }
        public string Currency { get; set; }
        public string BusinessRegistrationCertificate { get; set; }
        public string ShipViaCode { get; set; }
        public string ContactPerson { get; set; }
        public decimal CreditLimit { get; set; }
        public string PaymentTerm { get; set; }
        public string TerritoryID { get; set; }
        public string AttrName0 { get; set; }
        public string AttrName1 { get; set; }
        public string AttrName2 { get; set; }
        public string AttrName3 { get; set; }
        public string AttrName4 { get; set; }
        public string AttrName5 { get; set; }
        public string AttrName6 { get; set; }
        public string AttrName7 { get; set; }
        public string AttrName8 { get; set; }
        public string SystemLog { get; set; }
        public string DMSFlag { get; set; }
    }
}
