//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicorConsole.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EpicorIntegrationEntities : DbContext
    {
        public EpicorIntegrationEntities()
            : base("name=EpicorIntegrationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PRODUCT> PRODUCTs { get; set; }
        public virtual DbSet<PRICE_LIST> PRICE_LIST { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<PO_DETAIL> PO_DETAIL { get; set; }
        public virtual DbSet<PO_HEADER> PO_HEADER { get; set; }
        public virtual DbSet<ARINVOICE_HEADER> ARINVOICE_HEADER { get; set; }
        public virtual DbSet<ARINVOICE_DETAIL> ARINVOICE_DETAIL { get; set; }
    }
}
