//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicorConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVT_TRANS
    {
        public int Id { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public string DMSFlag { get; set; }
        public string Company { get; set; }
        public string Site { get; set; }
        public string PartDescription { get; set; }
        public string PartNum { get; set; }
        public string WareHouseCode { get; set; }
        public Nullable<System.DateTime> TranDate { get; set; }
        public Nullable<System.DateTime> SysDate { get; set; }
        public int OrderNum { get; set; }
        public string TranType { get; set; }
        public int TranNum { get; set; }
        public string TranClass { get; set; }
        public Nullable<decimal> TranQty { get; set; }
        public string LotNum { get; set; }
        public string InvtyUOM { get; set; }
    }
}
