//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicorConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVT_TRANS_HEADER
    {
        public string CompanyCode { get; set; }
        public string DocNum { get; set; }
        public string RefNum { get; set; }
        public string DocType { get; set; }
        public System.DateTime PostingDate { get; set; }
        public System.DateTime DocDate { get; set; }
        public string BranchCode { get; set; }
        public string Module { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string DMSFlag { get; set; }
    }
}
