//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicorConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_DETAIL
    {
        public int Id { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public string DMSFlag { get; set; }
        public string CompanyCode { get; set; }
        public int PONum { get; set; }
        public int POLine { get; set; }
        public string CalcTranType { get; set; }
        public string PartNum { get; set; }
        public string QtyOption { get; set; }
        public decimal CalcVendQty { get; set; }
        public string PUM { get; set; }
        public decimal DocUnitCost { get; set; }
        public decimal DocScrUnitCost { get; set; }
        public System.DateTime CalcDueDate { get; set; }
        public bool Taxable { get; set; }
        public bool RcvInspectionReq { get; set; }
        public string BranchCode { get; set; }
        public string WhsCode { get; set; }
    }
}
