//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicorConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_HEADER
    {
        public int Id { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public string DMSFlag { get; set; }
        public string Status { get; set; }
        public string CompanyCode { get; set; }
        public int PONum { get; set; }
        public string RefNum { get; set; }
        public string POType { get; set; }
        public string PaymentTerm { get; set; }
        public string Currency { get; set; }
        public string ShipViaCode { get; set; }
        public System.DateTime PostingDate { get; set; }
        public string ApprovalStatus { get; set; }
        public string ShipState { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public System.DateTime PODate { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime ShippingDate { get; set; }
        public string BranchCode { get; set; }
        public int VendorNumber { get; set; }
        public decimal POTotal { get; set; }
        public string Remarks { get; set; }
        public string EntryPerson { get; set; }
        public string BuyerID { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
    }
}
