//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicorConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceLstPart
    {
        public string Company { get; set; }
        public string ListCode { get; set; }
        public string PartNum { get; set; }
        public decimal BasePrice { get; set; }
        public decimal DiscountPercent1 { get; set; }
        public decimal DiscountPercent2 { get; set; }
        public decimal DiscountPercent3 { get; set; }
        public decimal DiscountPercent4 { get; set; }
        public decimal DiscountPercent5 { get; set; }
        public decimal QtyBreak1 { get; set; }
        public decimal QtyBreak2 { get; set; }
        public decimal QtyBreak3 { get; set; }
        public decimal QtyBreak4 { get; set; }
        public decimal QtyBreak5 { get; set; }
        public decimal UnitPrice1 { get; set; }
        public decimal UnitPrice2 { get; set; }
        public decimal UnitPrice3 { get; set; }
        public decimal UnitPrice4 { get; set; }
        public decimal UnitPrice5 { get; set; }
        public string CommentText { get; set; }
        public string UOMCode { get; set; }
        public bool GlobalPriceLstParts { get; set; }
        public bool GlobalLock { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
    }
}
