//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicorConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRICE_LIST
    {
        public int Id { get; set; }
        public string Company { get; set; }
        public string PriceListNum { get; set; }
        public string PriceListDesc { get; set; }
        public Nullable<System.DateTime> Startdate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public string Partnum { get; set; }
        public Nullable<int> BaseList { get; set; }
        public string SysRevID { get; set; }
        public string DMSFlag { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
    }
}
