//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicorConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public int Id { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string ForeignName { get; set; }
        public string BarCode { get; set; }
        public string Status { get; set; }
        public string SalesUnit { get; set; }
        public decimal SalesItemPerUnit { get; set; }
        public Nullable<decimal> SalesUnitLength { get; set; }
        public Nullable<decimal> SalesUnitWidth { get; set; }
        public Nullable<decimal> SalesUnitHeight { get; set; }
        public Nullable<decimal> SalesUnitVolume { get; set; }
        public Nullable<decimal> SalesUnitWeight { get; set; }
        public string SalesVATGroup { get; set; }
        public string PurchaseUnit { get; set; }
        public decimal PurchaseItemsPerUnit { get; set; }
        public Nullable<decimal> PurchaseUnitLength { get; set; }
        public Nullable<decimal> PurchaseUnitWidth { get; set; }
        public Nullable<decimal> PurchaseUnitHeight { get; set; }
        public Nullable<decimal> PurchaseUnitVolume { get; set; }
        public Nullable<decimal> PurchaseUnitWeight { get; set; }
        public string PurchaseVATGroup { get; set; }
        public string InventoryUOM { get; set; }
        public Nullable<decimal> MOQ { get; set; }
        public string AttrCode0 { get; set; }
        public string AttrName0 { get; set; }
        public string AttrCode01 { get; set; }
        public string AttrName01 { get; set; }
        public string AttrCode02 { get; set; }
        public string AttrName02 { get; set; }
        public string AttrCode03 { get; set; }
        public string AttrName03 { get; set; }
        public string AttrCode04 { get; set; }
        public string AttrName04 { get; set; }
        public string AttrCode05 { get; set; }
        public string AttrName05 { get; set; }
        public string AttrCode06 { get; set; }
        public string AttrName06 { get; set; }
        public string AttrCode07 { get; set; }
        public string AttrName07 { get; set; }
        public string AttrCode08 { get; set; }
        public string AttrName08 { get; set; }
        public string AttrCode09 { get; set; }
        public string AttrName09 { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public string DMSFlag { get; set; }
    }
}
