//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicorConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public int Id { get; set; }
        public string ItemCode { get; set; }
        public string Company { get; set; }
        public string ItemName { get; set; }
        public bool Status { get; set; }
        public string SalesUnit { get; set; }
        public decimal SalesItemsPerUnit { get; set; }
        public Nullable<decimal> SalesUnitLength { get; set; }
        public Nullable<decimal> SalesUnitWidth { get; set; }
        public Nullable<decimal> SalesUnitHeight { get; set; }
        public Nullable<decimal> SalesUnitVolume { get; set; }
        public Nullable<decimal> SalesUnitWeight { get; set; }
        public string SalesVATGroup { get; set; }
        public string PurchaseUnit { get; set; }
        public string InventoryUOM { get; set; }
        public string AttrCode0 { get; set; }
        public string AttrName0 { get; set; }
        public string AttrCode1 { get; set; }
        public string AttrName1 { get; set; }
        public string AttrCode2 { get; set; }
        public string AttrName2 { get; set; }
        public string AttrCode3 { get; set; }
        public string AttrName3 { get; set; }
        public string AttrCode4 { get; set; }
        public string AttrName4 { get; set; }
        public string AttrCode5 { get; set; }
        public string AttrName5 { get; set; }
        public string AttrCode6 { get; set; }
        public string AttrName6 { get; set; }
        public string AttrCode7 { get; set; }
        public string AttrName7 { get; set; }
        public string AttrCode8 { get; set; }
        public string AttrName8 { get; set; }
        public string AttrCode9 { get; set; }
        public string AttrName9 { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Option4 { get; set; }
        public string Option5 { get; set; }
        public string DMSFlag { get; set; }
        public string UD_SysRevID { get; set; }
        public string SysRevID { get; set; }
        public string TaxCode { get; set; }
        public string RateCode { get; set; }
    }
}
