//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicorConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO_HEADER
    {
        public string CompanyCode { get; set; }
        public string DocNum { get; set; }
        public int Ordernum { get; set; }
        public string BranchCode { get; set; }
        public string CustomerCode { get; set; }
        public string TermCode { get; set; }
        public string CurrencyCode { get; set; }
        public string Custnum { get; set; }
        public string BTCustnum { get; set; }
        public string ShiptoCustnum { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public decimal TotalAmount { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public string SystemLog { get; set; }
        public string DMSFlag { get; set; }
    }
}
